global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  # - job_name: prometheus
  #   static_configs:
  #     - targets: ['host.docker.internal:9004']
  # - job_name: pushgateway
  #   honor_labels: true
  #   static_configs:
  #     - targets: ['host.docker.internal:9091']
  # - job_name: kong_gateway
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: ['host.docker.internal:8001']
  - job_name: kong_plugin_metrics
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:9091']